spring:
  datasource:
    url: jdbc:mysql://localhost:3366/dsite?characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.example.SpringMybatisXml.Models.Users
  #config-location: classpath*:mapper/mybatis-config.xml